# Name: Updated Z-score Pipeline for Body Composition
# Author: Zhiwei Liang - integration of race-neutral z-score function.
# Original Author: Camden Bay - original author. Michael Rosenthal and Andrew Noble - modifications for deployment.
# Purpose: estimate race-specific and race-neutral BC z-scores for CT scan given a corresponding table of demographic data and BC areas

# LICENSE: This code is provided under AGPLv3.

# Note on the use of self-reported race in this data: Self-identified race captures a complex mixture of social
#    determinants of health that include socioeconomic status, historical disparities, inequitable access to care,
#    cultural patterns, and persistent structural inequities. Race-specific data are provided here to support
#    scientific understanding of these groups as they exist today, but80  great care should be taken to ensure that
#    race-specific metrics are not used in a way that reinforces historical disparities. Please see the following
#    article for additional discussion on this topic:
#
#    Vyas, D. A., Eisenstein, L. G., & Jones, D. S. (2020). Hidden in Plain Sight — Reconsidering the Use of Race
#    Correction in Clinical Algorithms. New England Journal of Medicine, 383(9), 874-882.
#    https://doi.org/10.1056/nejmms2004740



# Functions:
# z_scores(): function to calculate z-scores for either race-specific or race-neutral z-scores



#############################################################################################
# INSTALL REQUIRED PACKAGES ##################################################################
#############################################################################################

library(gamlss)
library(tidyverse)


#############################################################################################
# DEFINE I/O DIR PATHS AND SET WORKING DIR PATH ##############################################
#############################################################################################
INPUT_DIR <- "./input"
OUTPUT_DIR <- "./output"

#############################################################################################
# LOAD INPUTS ################################################################################
#############################################################################################
# The input table is expected to have the following columns:
# study_name: unique identifier for each exam
# ma, sa, va: skeletal muscle area, subcutaneous fat area, and visceral fat area, all in cm2
# age: in years at time of measurement
# sex: {'M' or 'F'}. Insufficient data available for nonbinary and other gender identities
# race: 'W' equals nonhispanic white/ caucasian. 'B' equals black. 'O' includes all other racial groupings and will not
#    return results until additional reference populations are analyzed.

df <- read_csv(file.path(INPUT_DIR, "zscores_input_example.csv")) # replace the file name as needed


# Load data of population LMS functions
# `perm_body_comp_lms_functions_no_phi.Rdata`: race-specific population lms functions generated by body comp cohort 2012
# `race_neutral_body_comp_lms_functions.Rdata`: race-neutral population lms functions generated by body comp cohort 2012

# race-specific lms functions
load("perm_body_comp_lms_functions_no_phi.Rdata")
# race-neutral lms functions
load("race_neutral_body_comp_lms_functions.Rdata")




#############################################################################################
# DEFINE Z-SCORE FUNCTION ##########################################################
#############################################################################################

# add `race_specific` parameter
# race_specific = TRUE, calculate race-specific z-scores, race column needed
# race_specific = FALSE, calculate race-neutral z-scores, race column not needed

z_scores <- function(age, sex, race = NULL, ma, sa, va, race_specific = TRUE) {
  if (race_specific) {
    # return NA if age, sex, or race is NaN or NA
    if (anyNA(c(age, sex, race))) {
      return(rep(NA, 3))
    }
    # return NA if age is < 20 or > 90;
    # this enforces the requirement that, for white females and males, ages > 90 years or < 20 years are out-of-bounds
    if (age < 20. || age > 90.) {
      return(rep(NA, 3))
    }
    # return NA if sex is not in c('F', 'M')
    if (!is.element(sex, c("F", "M"))) {
      return(rep(NA, 3))
    }
    # return NA if race is not in c('W', 'B')
    if (!is.element(race, c("W", "B"))) {
      return(rep(NA, 3))
    }
    # return NA for black females with age > 75 years
    if (sex == "F" && race == "B" && age > 75) {
      return(rep(NA, 3))
    }
    # return NA for black males with age > 70 years
    if (sex == "M" && race == "B" && age > 70) {
      return(rep(NA, 3))
    }
    # handle black female case
    if (sex == "F" && race == "B") {
      return(c(
        z.scores(lms_black_female_ma, x = age, y = ma),
        z.scores(lms_black_female_sa, x = age, y = sa),
        z.scores(lms_black_female_va, x = age, y = va)
      ))
    }
    # handle black male case
    if (sex == "M" && race == "B") {
      return(c(
        z.scores(lms_black_male_ma, x = age, y = ma),
        z.scores(lms_black_male_sa, x = age, y = sa),
        z.scores(lms_black_male_va, x = age, y = va)
      ))
    }
    # handle white female case
    if (sex == "F" && race == "W") {
      return(c(
        z.scores(lms_white_female_ma, x = age, y = ma),
        z.scores(lms_white_female_sa, x = age, y = sa),
        z.scores(lms_white_female_va, x = age, y = va)
      ))
    }
    # handle white male case
    if (sex == "M" && race == "W") {
      return(c(
        z.scores(lms_white_male_ma, x = age, y = ma),
        z.scores(lms_white_male_sa, x = age, y = sa),
        z.scores(lms_white_male_va, x = age, y = va)
      ))
    }
  } else {
    # return NA if age, sex is NaN or NA
    if (anyNA(c(age, sex))) {
      return(rep(NA, 3))
    }
    # return NA if sex is not in c('F', 'M')
    if (!is.element(sex, c("F", "M"))) {
      return(rep(NA, 3))
    }
    # female age boundaries: 20-80
    if (sex == "F" && (age < 20 || age > 80)) {
      return(rep(NA, 3))
    }
    # male age boundaries: 25-80
    if (sex == "M" && (age < 25 || age > 80)) {
      return(rep(NA, 3))
    }

    # handle female case
    if (sex == "F") {
      return(c(
        z.scores(lms_female_ma, x = age, y = ma),
        z.scores(lms_female_sa, x = age, y = sa),
        z.scores(lms_female_va, x = age, y = va)
      ))
    }
    # handle male case
    if (sex == "M") {
      return(c(
        z.scores(lms_male_ma, x = age, y = ma),
        z.scores(lms_male_sa, x = age, y = sa),
        z.scores(lms_male_va, x = age, y = va)
      ))
    }
  }
  return(rep(NA, 3)) # Fallthrough return
}




#############################################################################################
# ESTIMATE Z-SCORES FROM INPUT DATAFRAME ###############################################
#############################################################################################
# z-scores for race-specific
list_z_scores_race_specific <- pmap(df %>% select(age, sex, race, ma, sa, va), ~ z_scores(..., race_specific = TRUE))
df_z_scores_race_specific <- as_tibble(t(as.data.frame(list_z_scores_race_specific)))
colnames(df_z_scores_race_specific) <- c("ma_z_score", "sa_z_score", "va_z_score")
df_race_specific <- df %>% bind_cols(df_z_scores_race_specific)

# z-scores for race-neutral
list_z_scores_race_neutral <- pmap(df %>% select(age, sex, ma, sa, va), ~ z_scores(..., race_specific = FALSE))
df_z_scores_race_neutral <- as_tibble(t(as.data.frame(list_z_scores_race_neutral)))
colnames(df_z_scores_race_neutral) <- c("ma_z_score", "sa_z_score", "va_z_score")
df_race_neutral <- df %>% bind_cols(df_z_scores_race_neutral)




#############################################################################################
# WRITE Z-SCORE OUTPUT #######################################################################
#############################################################################################
# race-specific z-scores
write_csv(df_race_specific, file.path(OUTPUT_DIR, "zscores_output_example_race_specific.csv"), na = "")
# race-neutral z-scores
write_csv(df_race_neutral, file.path(OUTPUT_DIR, "zscores_output_example_race_neutral.csv"), na = "")
